http2: specify default TLS options for http2 client connection.
nodejs/http2 pull request #61
Opened 2017-05-02 18:36 UTC by jmuk

fixes: https://github.com/nodejs/http2/issues/59

2017-05-02 19:25 UTC, mcollina requested changes
can you also add a unit test for this?

2017-05-02 19:25 UTC, mcollina commented on lib/internal/http2/core.js
> +      }, options);
I would prefer `Object.assign`

2017-05-02 21:16 UTC, jasnell commented
Had a different approach in mind for fixing this: 

```js
diff --git a/lib/internal/http2/core.js b/lib/internal/http2/core.js
index 6afc87e6f7..052513289f 100755
--- a/lib/internal/http2/core.js
+++ b/lib/internal/http2/core.js
@@ -1077,6 +1077,7 @@ function initializeOptions(options) {
   options = options || {};
   if (typeof options !== 'object')
     throw new TypeError('options must be an object');
+  options = Object.create(options);
   options.allowHalfOpen = true;
   options.settings = options.settings || {};
   if (typeof options.settings !== 'object')
@@ -1084,10 +1085,12 @@ function initializeOptions(options) {
   return options;
 }

-function initializeTLSOptions(options) {
+function initializeTLSOptions(options, host) {
   options = initializeOptions(options);
   options.ALPNProtocols = ['hc', 'h2'];
   options.NPNProtocols = ['hc', 'h2'];
+  if (host !== undefined)
+    options.servername = host;
   return options;
 }

@@ -1235,7 +1238,7 @@ function connect(authority, options, listener) {
       socket = net.connect(port, host);
       break;
     case 'https:':
-      socket = tls.connect(port, host, options);
+      socket = tls.connect(port, host, initializeTLSOptions(options, host));
       break;
     default:
       throw new TypeError(`protocol "${protocol}" in unsupported.`);
james@ubuntu:~/node/http2-jasnell$
```

This allows us to have a central place for setting the TLS options for both server and client.

2017-05-02 22:10 UTC, jmuk commented
Thank you for the review!  Added a test case, and fixed the client code for your latter suggestion.

2017-05-02 22:10 UTC, jmuk commented
By the way -- where does the ALPN name `'hc'` come from? I can't find the document referring that value -- http2 spec would suggest to use `h2` only for TLS context, I suppose (see https://http2.github.io/http2-spec/#rfc.section.3.1).

2017-05-02 22:19 UTC, jasnell commented
I think it's an old pre-standard value. One of the browser impls was using it. Whether or not we need to keep it remains to be seen

2017-05-03 07:09 UTC, mcollina commented on test/parallel/test-http2-create-client-secure-session.js
> +    }
why are you repeating this test 10 times?

2017-05-04 00:41 UTC, jmuk commented on test/parallel/test-http2-create-client-secure-session.js
> +    }
I borrowed the structure from `test/parallel/test-http2-create-client-session.js` which also repeats 10 times (https://github.com/nodejs/http2/blob/master/test/parallel/test-http2-create-client-session.js), I think it's better to have the same structure here. Should I change here, or both?

2017-05-04 11:38 UTC, jasnell commented on test/parallel/test-http2-create-client-secure-session.js
> +    }
the calling ten times in the other test is an artifact from trying to trace down a bug I was working through. I actually need to refactor that test to pull that back out :-)

2017-05-04 19:00 UTC, jmuk commented
Removed the count, thank you for the background info.

2017-05-05 04:44 UTC, jasnell approved these changes

2017-05-05 06:25 UTC, jasnell commented
@mcollina ... ping

2017-05-05 08:13 UTC, mcollina approved these changes

2017-05-05 08:13 UTC, mcollina commented
LGTM

2017-05-07 09:01 UTC, jasnell commented
Landed!

2017-05-07 09:01 UTC, closed without merging